# Generated by Django 5.2.7 on 2025-11-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('default_intelligence_level', models.CharField(default='super', max_length=20)),
                ('preferred_response_style', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed'), ('technical', 'Technical'), ('casual', 'Casual'), ('quantum', 'Quantum Consciousness')], default='detailed', max_length=50)),
                ('system_info_preferences', models.JSONField(blank=True, default=dict)),
                ('notification_settings', models.JSONField(blank=True, default=dict)),
                ('ui_preferences', models.JSONField(blank=True, default=dict)),
                ('privacy_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_identifier'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_identifier', models.CharField(db_index=True, default='anonymous', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('intelligence_level', models.CharField(choices=[('nano', 'Nano'), ('standard', 'Standard'), ('super', 'Super'), ('quantum', 'Quantum')], default='super', max_length=20)),
                ('total_messages', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['session_id', 'user_identifier'], name='quantum_goo_session_ac180e_idx'), models.Index(fields=['last_active'], name='quantum_goo_last_ac_57b70b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('system', 'System Information'), ('api', 'API Documentation'), ('tutorial', 'Tutorial/Guide'), ('faq', 'FAQ'), ('technical', 'Technical Knowledge'), ('quantum', 'Quantum Concepts'), ('general', 'General Knowledge')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-relevance_score', '-updated_at'],
                'indexes': [models.Index(fields=['category', 'relevance_score'], name='quantum_goo_categor_df5399_idx'), models.Index(fields=['title'], name='quantum_goo_title_71ad15_idx')],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=255)),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('context', 'Context'), ('knowledge', 'Knowledge'), ('system', 'System')], default='fact', max_length=20)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('importance', models.IntegerField(default=5, help_text='1-10 scale, higher = more important')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-importance', '-updated_at'],
                'indexes': [models.Index(fields=['user_identifier', 'memory_type'], name='quantum_goo_user_id_968b05_idx'), models.Index(fields=['key'], name='quantum_goo_key_fac97d_idx'), models.Index(fields=['importance', 'is_active'], name='quantum_goo_importa_57d641_idx')],
                'unique_together': {('user_identifier', 'key')},
            },
        ),
        migrations.CreateModel(
            name='MemorySearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100)),
                ('relevance', models.FloatField(default=1.0)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='quantum_goose_app.memory')),
            ],
            options={
                'indexes': [models.Index(fields=['keyword', 'relevance'], name='quantum_goo_keyword_8d5573_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('token_count', models.IntegerField(default=0)),
                ('intelligence_level', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quantum_goose_app.conversationsession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='quantum_goo_session_68b05d_idx'), models.Index(fields=['role', 'timestamp'], name='quantum_goo_role_81c495_idx')],
            },
        ),
    ]
